### ISSUE TITLE
Parse Error bei Leerzeichen zwischen verschachtelten Abstraktionen ohne Klammern

### ISSUE THREAD

**Issue by iTob191** [SrTobi/lambda#1]
`(\x.\y.b) a` funktioniert und liefert `(\x.\y.b) a => \y.b`
`(\x.\y. b) a` funktioniert und liefert das gleiche
`(\x. \y. b) a` liefert `Error: Expected "(" but "\\" found. in line 1, column 6`
`(\x. (\y. b)) a` wiederum funktioniert wie oben

Ist das Absicht, dass das Leerzeichen da en Parse Error liefert? Und die Fehlermeldung is en bissl viel escaped :D

**Comment by SrTobi** [comment]
Thx, I fixed the grammar
